import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

  openGraph: {
    title: "Title webtsite",
    description: "this is the desciption",
    images: "url/image.png",
  },
  twitter: {
    card: "summary_large_image",
    site: "@Aniketsahoo18",
    title: "Title webtsite",
    description: "this is the desciption",
    images: "url/image.png",
  },
};
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
